apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: cert-manager
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: bakke
  kubernetes:
    role: trust-manager 
    serviceAccount: trust-manager
