apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: vault-ca-secret
  namespace: cert-manager
spec:
  vaultAuthRef: vault-auth
  mount: pki_int1
  path: issuer/default/json
  destination:
    create: true
    name: vault-ca
